<script>
  import { t, locale } from '@le-space/landing-shared/i18n';
  import { publicDecks } from '@le-space/landing-shared/use-cases';

  // The decks themselves are static files generated by tools/build-decks.mjs
  // into public/use-cases/. This section only links to them, from the same data.
  const deckUrl = (deck) => `/use-cases/${deck.id}/?lang=${$locale}`;
  const pdfUrl = (deck) => `/use-cases/${deck.id}/${deck.id}-pitch-${$locale}.pdf`;
</script>

<section id="use-cases" class="ls-section">
  <div class="ls-container">
    <h2 class="ls-section-title">{$t('usecases.title')}</h2>
    <p class="ls-section-sub">{$t('usecases.sub')}</p>

    <div class="grid">
      {#each publicDecks as deck (deck.id)}
        <article class="card" style="--accent:{deck.accent}">
          <div class="head">
            <span class="letter">{deck.letter}</span>
            <div>
              <h3>{deck.name}</h3>
              <p class="sub">{deck.subtitle[$locale] || deck.subtitle.en}</p>
            </div>
          </div>
          <p class="teaser">{deck.teaser[$locale] || deck.teaser.en}</p>
          <div class="links">
            <a class="btn primary" href={deckUrl(deck)}>{$t('usecases.open')}</a>
            <a class="btn" href={pdfUrl(deck)} download>{$t('usecases.pdf')}</a>
            {#if deck.links.github}
              <a class="btn" href={deck.links.github} target="_blank" rel="noopener noreferrer">
                {$t('projects.source')}
              </a>
            {/if}
          </div>
        </article>
      {/each}
    </div>
  </div>
</section>

<style>
  .grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(340px, 1fr));
    gap: 22px;
  }

  .card {
    background: var(--ls-card);
    border: 1px solid var(--ls-card-border);
    border-radius: var(--ls-radius);
    padding: 24px;
    display: flex;
    flex-direction: column;
    transition: border-color 0.25s ease, transform 0.25s ease;
  }

  .card:hover {
    border-color: var(--accent);
    transform: translateY(-3px);
  }

  .head {
    display: flex;
    gap: 14px;
    align-items: flex-start;
    margin-bottom: 14px;
  }

  .letter {
    flex: none;
    width: 36px;
    height: 36px;
    display: grid;
    place-items: center;
    border-radius: 10px;
    border: 1px solid var(--accent);
    color: var(--accent);
    font-family: var(--ls-font-mono);
    font-weight: 700;
  }

  h3 {
    margin: 0;
    font-size: 1.2rem;
  }

  .sub {
    margin: 2px 0 0;
    color: var(--ls-text-dim);
    font-size: 0.92rem;
  }

  .teaser {
    color: var(--ls-text-dim);
    margin: 0 0 20px;
    flex: 1;
  }

  .links {
    display: flex;
    flex-wrap: wrap;
    gap: 10px;
  }

  .btn {
    padding: 8px 16px;
    border-radius: var(--ls-radius-sm);
    border: 1px solid var(--ls-card-border);
    color: var(--ls-text);
    font-size: 0.9rem;
    font-weight: 600;
  }

  .btn:hover {
    text-decoration: none;
    background: var(--ls-card-hover);
  }

  .btn.primary {
    background: var(--ls-red);
    border-color: var(--ls-red);
    color: #fff;
  }

  .btn.primary:hover {
    box-shadow: var(--ls-glow-red);
    background: var(--ls-red);
  }
</style>
